name: Build Kernel

on:
  push:
    paths:
      - '.github/workflows/build_kernel.yml'
      - 'kernel/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu
          key: gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu

      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: kernel-4.14
        run: |
          sudo apt install axel
          axel -a -n 10 https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
          tar xvf *tar.xz  -C ./

      - name: Build kernel
        working-directory: kernel-4.14
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$(pwd)/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin/aarch64-linux-gnu-
          make a05bd_defconfig
          make -j2

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TAB-A05-BD-kernel
          path: |
            kernel/arch/arm64/boot/*
          if-no-files-found: ignore
