name: Build Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add Xenial repository
        run: sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"

      - name: Update package list
        run: sudo apt-get update

      - name: Install GCC 7
        run: |
          sudo apt-get install -y gcc-7 g++-7 gcc-7-aarch64-linux-gnu

      - name: Set up cross-compiler
        run: |
          sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-7 /usr/bin/aarch64-linux-gnu-gcc
          echo "/usr/bin" >> $GITHUB_PATH

      - name: Build kernel
        working-directory: kernel-4.14
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make a05bd_defconfig
          make -j8

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TAB-A05-BD-kernel
          path: |
            kernel/arch/arm64/boot/*
          if-no-files-found: ignore
